// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaafehkpcqqjutjwjfey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYWZlaGtwY3FxanV0andqZmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTEyNzYsImV4cCI6MjA2OTk4NzI3Nn0.KZQVfuKJR3rGoBVPSH5uEEaqkYFAl_RNaulITmzMeiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});